server:
  port: 8080

spring:
  application:
    name: payments-service
  kafka:
    admin:
      client-id:
    client-id:


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://43.200.189.164:8761/eureka

payment:

  key:
    cid: "TC0ONETIME"
    app_admin_key: "5192b723fd59e84d94d34bbb004c6c5a"

  redirect_url:
    approval_url: "http://localhost:8081"
    cancel_url: "http://localhost:8082"
    fail_url: "http://localhost:8083"

  provider:
    ready_uri: "https://kapi.kakao.com/v1/payment/ready"
    approve_uri: "https://kapi.kakao.com/v1/payment/approve"