server:
  port: 8080

spring:

  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/user

  security:
    payment:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: cd2447cf90f5929ed98bc599d51f323d
            client-secret: FEcBzqUhgg02OgA3R58yYXsU4Wb7TgGR
            redirect-uri: http://localhost:8080
            authorization-grant-type: authorization_code
            scope:
            #              - account_email
            #              - profile_nickname
            #              - profile_image
            client-authentication-method: POST
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
  #            user-name-attribute: id

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://43.200.189.164:8761/eureka